import PDFDocument from "pdfkit";

/**
 * Format a Date object to "DD Month YYYY"
 */
export const formatDate = (date) => {
  if (!date) return "—";
  const d = new Date(date);
  if (isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
};

/**
 * Helper to render standard company letterhead
 */
const renderLetterhead = (doc, organization, primaryColor = "#6C5CE7") => {
  const pageWidth = doc.page.width;
  const marginX = 50;
  const contentWidth = pageWidth - marginX * 2;

  const orgName = organization?.name || "The Organization";
  const orgAddress = organization?.address || "";
  const orgEmail = organization?.contactEmail || "";
  const orgPhone = organization?.contactPhone || "";

  // Top accent bar
  doc.rect(0, 0, pageWidth, 8).fill(primaryColor);

  let y = 35;
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor("#1E293B")
    .text(orgName.toUpperCase(), marginX, y, { width: contentWidth, align: "left" });

  y += 24;

  const contactParts = [];
  if (orgAddress) contactParts.push(orgAddress);
  if (orgEmail) contactParts.push(`Email: ${orgEmail}`);
  if (orgPhone) contactParts.push(`Phone: ${orgPhone}`);

  if (contactParts.length > 0) {
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#64748B")
      .text(contactParts.join("  |  "), marginX, y, {
        width: contentWidth,
        align: "left",
      });
    y += 18;
  }

  // Divider
  doc
    .moveTo(marginX, y)
    .lineTo(pageWidth - marginX, y)
    .strokeColor("#E2E8F0")
    .lineWidth(1)
    .stroke();

  return y + 16;
};

/**
 * Helper to render standard document footer
 */
const renderFooter = (doc, signatoryTitle = "Human Resources Department", orgName = "The Organization") => {
  const pageWidth = doc.page.width;
  const marginX = 50;
  const contentWidth = pageWidth - marginX * 2;

  let y = doc.y + 24;
  if (y > 680) {
    doc.addPage();
    y = 50;
  }

  doc.font("Helvetica").fontSize(10).fillColor("#1F2937");
  doc.text("Sincerely,", marginX, y);
  y += 14;

  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1E293B");
  doc.text(`For ${orgName}`, marginX, y);
  y += 36;

  // Signature line
  doc
    .moveTo(marginX, y)
    .lineTo(marginX + 170, y)
    .strokeColor("#94A3B8")
    .lineWidth(1)
    .stroke();

  y += 6;
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1E293B");
  doc.text("Authorized Signatory", marginX, y);
  y += 14;

  doc.font("Helvetica").fontSize(9).fillColor("#64748B");
  doc.text(signatoryTitle, marginX, y);

  // Bottom confidentiality note
  const bottomY = doc.page.height - 35;
  doc
    .font("Helvetica-Oblique")
    .fontSize(8)
    .fillColor("#94A3B8")
    .text(
      "This is an official document generated by the Human Resource Management System.",
      marginX,
      bottomY,
      { width: contentWidth, align: "center" }
    );
};

// =============================================================================
// 1. NO-DUES CLEARANCE CERTIFICATE PDF
// =============================================================================
export const createNoDuesCertificatePDF = ({
  offboarding,
  employee,
  organization,
  compress = false,
}) => {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true, compress });
  const marginX = 50;
  const contentWidth = doc.page.width - marginX * 2;

  const orgName = organization?.name || "Infinetra Technologies";
  const orgCode = organization?.orgCode || organization?.code || "INF";
  const user = employee?.user_id || {};
  const empName = user.name || "Employee";
  const empCode = employee?.employee_code || "EMP";
  const designation = employee?.designation || "Employee";
  const deptName = employee?.department_id?.departmentName || user.department || "General";

  const lwdFormatted = formatDate(offboarding?.last_working_day);
  const issueDateFormatted = formatDate(new Date());
  const year = new Date().getFullYear();
  const refNumber = `NDC/${orgCode}/${empCode}/${year}`;

  let y = renderLetterhead(doc, organization, "#059669"); // Emerald theme

  // Ref & Date
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#64748B").text(`Ref: ${refNumber}`, marginX, y);
  doc.font("Helvetica").fontSize(9).fillColor("#64748B").text(`Date: ${issueDateFormatted}`, marginX, y, {
    width: contentWidth,
    align: "right",
  });
  y += 26;

  // Title
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#64748B").text("TO WHOMSOEVER IT MAY CONCERN", marginX, y, {
    width: contentWidth,
    align: "center",
    characterSpacing: 1,
  });
  y += 18;

  doc.font("Helvetica-Bold").fontSize(16).fillColor("#059669").text("NO-DUES CLEARANCE CERTIFICATE", marginX, y, {
    width: contentWidth,
    align: "center",
  });
  y += 26;

  // Body
  doc.font("Helvetica").fontSize(10.5).fillColor("#1F2937");
  const p1 = `This is to certify that ${empName} (Employee Code: ${empCode}), who was employed with ${orgName} as ${designation} in the ${deptName} department until their last working day on ${lwdFormatted}, has completed all exit clearance and handover procedures.`;
  doc.text(p1, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });
  y = doc.y + 12;

  // Clearance Summary Box
  doc.rect(marginX, y, contentWidth, 140).fillAndStroke("#F0FDF4", "#BBF7D0");
  const boxInnerY = y + 12;

  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#065F46").text("CLEARANCE VERIFICATION SUMMARY:", marginX + 16, boxInnerY);

  const clearance = offboarding?.clearance_status || {};
  const depts = [
    { label: "1. Human Resources Clearance", status: clearance.hr?.signed ? "Approved / Cleared" : "Pending", date: formatDate(clearance.hr?.signed_at) },
    { label: "2. IT & Infrastructure Assets", status: clearance.it?.signed ? "Approved / Returned" : "Pending", date: formatDate(clearance.it?.signed_at) },
    { label: "3. Finance & Accounts Settlement", status: clearance.finance?.signed ? "Approved / Settled" : "Pending", date: formatDate(clearance.finance?.signed_at) },
    { label: "4. Department / Manager Handover", status: clearance.manager?.signed ? "Approved / Completed" : "Pending", date: formatDate(clearance.manager?.signed_at) },
  ];

  let itemY = boxInnerY + 22;
  depts.forEach((item) => {
    doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#1E293B").text(item.label, marginX + 20, itemY);
    doc.font("Helvetica").fontSize(9).fillColor("#047857").text(`✓  ${item.status} (${item.date})`, marginX + 260, itemY);
    itemY += 24;
  });

  y += 156;

  // Affirmation
  doc.font("Helvetica").fontSize(10.5).fillColor("#1F2937");
  const p2 = `All company property, hardware devices, software credentials, and organizational records have been accounted for and returned in satisfactory condition. The accounts department confirms that all salary settlements, financial dues, and claims have been fully reconciled.`;
  doc.text(p2, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });
  y = doc.y + 10;

  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#065F46");
  const p3 = `The management hereby confirms that there are NO OUTSTANDING DUES, FINANCIAL LIABILITIES, OR UNRETURNED ASSETS pending against ${empName} as of this date.`;
  doc.text(p3, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });

  renderFooter(doc, "Human Resources & Clearance Administration", orgName);
  return doc;
};

// =============================================================================
// 2. RELIEVING LETTER PDF (OPTION A: CONCISE RESIGNATION RELEASE LETTER)
// =============================================================================
export const createRelievingLetterPDF = ({
  offboarding,
  employee,
  organization,
  compress = false,
}) => {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true, compress });
  const marginX = 50;
  const contentWidth = doc.page.width - marginX * 2;

  const orgName = organization?.name || "Infinetra Technologies";
  const orgCode = organization?.orgCode || organization?.code || "INF";
  const user = employee?.user_id || {};
  const empName = user.name || "Employee";
  const empCode = employee?.employee_code || "EMP";
  const designation = employee?.designation || "Employee";
  const deptName = employee?.department_id?.departmentName || user.department || "General";

  const resignFormatted = formatDate(offboarding?.resignation_date);
  const lwdFormatted = formatDate(offboarding?.last_working_day);
  const issueDateFormatted = formatDate(new Date());
  const year = new Date().getFullYear();
  const refNumber = `REL/${orgCode}/${empCode}/${year}`;

  let y = renderLetterhead(doc, organization, "#2563EB"); // Royal blue theme

  // Ref & Date
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#64748B").text(`Ref: ${refNumber}`, marginX, y);
  doc.font("Helvetica").fontSize(9).fillColor("#64748B").text(`Date: ${issueDateFormatted}`, marginX, y, {
    width: contentWidth,
    align: "right",
  });
  y += 26;

  // Addressee
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1E293B").text("To,", marginX, y);
  y += 14;
  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1E293B").text(empName, marginX, y);
  y += 14;
  doc.font("Helvetica").fontSize(9.5).fillColor("#64748B").text(`Employee Code: ${empCode}  |  Designation: ${designation}`, marginX, y);
  y += 14;
  doc.font("Helvetica").fontSize(9.5).fillColor("#64748B").text(`Department: ${deptName}`, marginX, y);
  y += 24;

  // Title
  doc.font("Helvetica-Bold").fontSize(15).fillColor("#1D4ED8").text("RELIEVING ORDER & SERVICE DISCHARGE", marginX, y, {
    width: contentWidth,
    align: "center",
  });
  y += 24;

  // Salutation & Body
  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1E293B").text(`Dear ${empName},`, marginX, y);
  y += 18;

  doc.font("Helvetica").fontSize(10.5).fillColor("#1F2937");
  const p1 = `This has reference to your letter of resignation dated ${resignFormatted}, tendering your resignation from the services of ${orgName}.`;
  doc.text(p1, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });
  y = doc.y + 10;

  const p2 = `We wish to inform you that your resignation has been formally accepted by the management. Consequently, you are officially relieved from all your duties and responsibilities as ${designation} in the ${deptName} department with effect from the close of business hours on ${lwdFormatted}.`;
  doc.text(p2, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });
  y = doc.y + 10;

  const p3 = `You have completed all handover formalities and department sign-offs satisfactorily. All company records, documentation, and property entrusted to your care have been returned and verified.`;
  doc.text(p3, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });
  y = doc.y + 12;

  const p4 = `We take this opportunity to thank you for your service and valuable contributions to ${orgName}, and we wish you success, prosperity, and fulfillment in all your future professional endeavors.`;
  doc.text(p4, marginX, y, { width: contentWidth, align: "justify", lineGap: 4 });

  renderFooter(doc, "Human Resources Management", orgName);
  return doc;
};

// =============================================================================
// 3. TENURE ATTENDANCE SUMMARY STATEMENT PDF
// =============================================================================
export const createAttendanceSummaryPDF = ({
  offboarding,
  employee,
  organization,
  attendanceRecords = [],
  startDate,
  compress = false,
}) => {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true, compress });
  const marginX = 50;
  const contentWidth = doc.page.width - marginX * 2;

  const orgName = organization?.name || "Infinetra Technologies";
  const user = employee?.user_id || {};
  const empName = user.name || "Employee";
  const empCode = employee?.employee_code || "EMP";
  const designation = employee?.designation || "Employee";
  const deptName = employee?.department_id?.departmentName || user.department || "General";

  const startFormatted = formatDate(startDate || employee?.date_of_joining);
  const lwdFormatted = formatDate(offboarding?.last_working_day);
  const issueDateFormatted = formatDate(new Date());

  let y = renderLetterhead(doc, organization, "#0284C7"); // Sky/cyan theme

  doc.font("Helvetica").fontSize(9).fillColor("#64748B").text(`Date: ${issueDateFormatted}`, marginX, y, {
    width: contentWidth,
    align: "right",
  });
  y += 18;

  // Title
  doc.font("Helvetica-Bold").fontSize(15).fillColor("#0369A1").text("TENURE ATTENDANCE SUMMARY STATEMENT", marginX, y, {
    width: contentWidth,
    align: "center",
  });
  y += 20;

  // Employee Details Strip
  doc.rect(marginX, y, contentWidth, 34).fillAndStroke("#F0F9FF", "#BAE6FD");
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#0369A1").text(`${empName} (${empCode})`, marginX + 12, y + 10);
  doc.font("Helvetica").fontSize(9).fillColor("#334155").text(`${designation} • ${deptName} • Tenure: ${startFormatted} to ${lwdFormatted}`, marginX + 180, y + 10, { width: contentWidth - 190 });
  y += 46;

  // Calculate metrics
  const totalLogs = attendanceRecords.length;
  let presentDays = 0;
  let lateDays = 0;
  let halfDays = 0;

  attendanceRecords.forEach((rec) => {
    const s = (rec.status || "").toLowerCase();
    if (s === "present") presentDays++;
    else if (s === "late") lateDays++;
    else if (s === "half day") halfDays++;
  });

  const totalEffectivePresent = presentDays + lateDays + halfDays * 0.5;
  const attendancePct = totalLogs > 0 ? ((totalEffectivePresent / totalLogs) * 100).toFixed(1) : "100.0";

  // Metrics Box
  doc.rect(marginX, y, contentWidth, 68).fillAndStroke("#F8FAFC", "#E2E8F0");
  const colW = contentWidth / 4;

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("RECORDED LOGS", marginX + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#0F172A").text(`${totalLogs}`, marginX + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text("Total Shift Entries", marginX + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("PRESENT DAYS", marginX + colW + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#16A34A").text(`${presentDays}`, marginX + colW + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text("On-Time Full Shifts", marginX + colW + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("LATE / HALF DAYS", marginX + colW * 2 + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#D97706").text(`${lateDays + halfDays}`, marginX + colW * 2 + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text(`${lateDays} Late, ${halfDays} Half`, marginX + colW * 2 + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("ATTENDANCE RATE", marginX + colW * 3 + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#0284C7").text(`${attendancePct}%`, marginX + colW * 3 + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text("Effective Compliance", marginX + colW * 3 + 10, y + 48);

  y += 82;

  // Monthly Breakdown Table
  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1E293B").text("MONTHLY ATTENDANCE AUDIT LOG:", marginX, y);
  y += 14;

  // Group by Month/Year
  const monthlyGroups = {};
  attendanceRecords.forEach((rec) => {
    const d = new Date(rec.date);
    if (isNaN(d.getTime())) return;
    const key = `${d.toLocaleString("en-IN", { month: "short" })} ${d.getFullYear()}`;
    if (!monthlyGroups[key]) {
      monthlyGroups[key] = { monthYear: key, total: 0, present: 0, late: 0, halfDay: 0 };
    }
    monthlyGroups[key].total++;
    const s = (rec.status || "").toLowerCase();
    if (s === "present") monthlyGroups[key].present++;
    else if (s === "late") monthlyGroups[key].late++;
    else if (s === "half day") monthlyGroups[key].halfDay++;
  });

  const months = Object.values(monthlyGroups).slice(0, 12); // Up to 12 months for clean layout

  // Table Header
  doc.rect(marginX, y, contentWidth, 22).fill("#0284C7");
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#FFFFFF");
  doc.text("Month / Year", marginX + 10, y + 6, { width: 120 });
  doc.text("Total Logs", marginX + 140, y + 6, { width: 70, align: "center" });
  doc.text("Present", marginX + 220, y + 6, { width: 70, align: "center" });
  doc.text("Late / Half", marginX + 300, y + 6, { width: 80, align: "center" });
  doc.text("Attendance %", marginX + 390, y + 6, { width: 90, align: "center" });
  y += 22;

  if (months.length === 0) {
    doc.rect(marginX, y, contentWidth, 24).fillAndStroke("#FFFFFF", "#E2E8F0");
    doc.font("Helvetica").fontSize(9).fillColor("#64748B").text("No attendance logs recorded in this period.", marginX, y + 7, { width: contentWidth, align: "center" });
    y += 24;
  } else {
    months.forEach((m, idx) => {
      const bg = idx % 2 === 0 ? "#FFFFFF" : "#F8FAFC";
      doc.rect(marginX, y, contentWidth, 20).fillAndStroke(bg, "#E2E8F0");
      const mEffective = m.present + m.late + m.halfDay * 0.5;
      const mPct = m.total > 0 ? ((mEffective / m.total) * 100).toFixed(1) : "100.0";

      doc.font("Helvetica").fontSize(8.5).fillColor("#1E293B").text(m.monthYear, marginX + 10, y + 5);
      doc.text(String(m.total), marginX + 140, y + 5, { width: 70, align: "center" });
      doc.font("Helvetica-Bold").fillColor("#16A34A").text(String(m.present), marginX + 220, y + 5, { width: 70, align: "center" });
      doc.font("Helvetica").fillColor("#D97706").text(String(m.late + m.halfDay), marginX + 300, y + 5, { width: 80, align: "center" });
      doc.font("Helvetica-Bold").fillColor("#0284C7").text(`${mPct}%`, marginX + 390, y + 5, { width: 90, align: "center" });
      y += 20;
    });
  }

  y += 12;
  doc.font("Helvetica-Oblique").fontSize(8.5).fillColor("#64748B").text("Note: Attendance calculations represent verified electronic check-in logs during employment.", marginX, y);

  renderFooter(doc, "Attendance & Operations Department", orgName);
  return doc;
};

// =============================================================================
// 4. TENURE LEAVE SUMMARY STATEMENT PDF
// =============================================================================
export const createLeaveSummaryPDF = ({
  offboarding,
  employee,
  organization,
  leaveRecords = [],
  startDate,
  compress = false,
}) => {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true, compress });
  const marginX = 50;
  const contentWidth = doc.page.width - marginX * 2;

  const orgName = organization?.name || "Infinetra Technologies";
  const user = employee?.user_id || {};
  const empName = user.name || "Employee";
  const empCode = employee?.employee_code || "EMP";
  const designation = employee?.designation || "Employee";
  const deptName = employee?.department_id?.departmentName || user.department || "General";

  const startFormatted = formatDate(startDate || employee?.date_of_joining);
  const lwdFormatted = formatDate(offboarding?.last_working_day);
  const issueDateFormatted = formatDate(new Date());

  let y = renderLetterhead(doc, organization, "#7C3AED"); // Violet theme

  doc.font("Helvetica").fontSize(9).fillColor("#64748B").text(`Date: ${issueDateFormatted}`, marginX, y, {
    width: contentWidth,
    align: "right",
  });
  y += 18;

  // Title
  doc.font("Helvetica-Bold").fontSize(15).fillColor("#6D28D9").text("TENURE LEAVE & ACCRUAL STATEMENT", marginX, y, {
    width: contentWidth,
    align: "center",
  });
  y += 20;

  // Employee Details Strip
  doc.rect(marginX, y, contentWidth, 34).fillAndStroke("#F5F3FF", "#DDD6FE");
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#6D28D9").text(`${empName} (${empCode})`, marginX + 12, y + 10);
  doc.font("Helvetica").fontSize(9).fillColor("#334155").text(`${designation} • ${deptName} • Tenure: ${startFormatted} to ${lwdFormatted}`, marginX + 180, y + 10, { width: contentWidth - 190 });
  y += 46;

  // Tally approved leaves
  let totalApprovedDays = 0;
  let annualDays = 0;
  let sickDays = 0;
  let casualDays = 0;

  const approvedLeaves = leaveRecords.filter((l) => (l.status || "").toLowerCase() === "approved");

  approvedLeaves.forEach((l) => {
    const s = new Date(l.startDate);
    const e = new Date(l.endDate);
    let diffDays = 1;
    if (!isNaN(s.getTime()) && !isNaN(e.getTime())) {
      diffDays = Math.max(1, Math.round((e - s) / (1000 * 60 * 60 * 24)) + 1);
    }
    totalApprovedDays += diffDays;
    const t = (l.leaveType || "").toLowerCase();
    if (t.includes("annual") || t.includes("privilege")) annualDays += diffDays;
    else if (t.includes("sick") || t.includes("medical")) sickDays += diffDays;
    else casualDays += diffDays;
  });

  // Metrics Box
  doc.rect(marginX, y, contentWidth, 68).fillAndStroke("#F8FAFC", "#E2E8F0");
  const colW = contentWidth / 4;

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("TOTAL REQUESTS", marginX + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#0F172A").text(`${leaveRecords.length}`, marginX + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text("Filed in System", marginX + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("APPROVED LEAVES", marginX + colW + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#7C3AED").text(`${totalApprovedDays} days`, marginX + colW + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text(`${approvedLeaves.length} Approved Requests`, marginX + colW + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("ANNUAL / CASUAL", marginX + colW * 2 + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#2563EB").text(`${annualDays + casualDays} days`, marginX + colW * 2 + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text(`${annualDays} Annual, ${casualDays} Casual`, marginX + colW * 2 + 10, y + 48);

  doc.font("Helvetica").fontSize(8.5).fillColor("#64748B").text("SICK / MEDICAL", marginX + colW * 3 + 10, y + 12);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#DC2626").text(`${sickDays} days`, marginX + colW * 3 + 10, y + 26);
  doc.font("Helvetica").fontSize(8).fillColor("#94A3B8").text("Certified Medical Leaves", marginX + colW * 3 + 10, y + 48);

  y += 82;

  // Itemized Leave History Table
  doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1E293B").text("ITEMIZED APPROVED LEAVES RECORD:", marginX, y);
  y += 14;

  // Table Header
  doc.rect(marginX, y, contentWidth, 22).fill("#7C3AED");
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#FFFFFF");
  doc.text("Leave Type", marginX + 10, y + 6, { width: 90 });
  doc.text("Start Date", marginX + 105, y + 6, { width: 75 });
  doc.text("End Date", marginX + 185, y + 6, { width: 75 });
  doc.text("Duration", marginX + 265, y + 6, { width: 55, align: "center" });
  doc.text("Status", marginX + 325, y + 6, { width: 65, align: "center" });
  doc.text("Reason / Purpose", marginX + 395, y + 6, { width: 95 });
  y += 22;

  if (approvedLeaves.length === 0) {
    doc.rect(marginX, y, contentWidth, 24).fillAndStroke("#FFFFFF", "#E2E8F0");
    doc.font("Helvetica").fontSize(9).fillColor("#64748B").text("No approved leaves recorded during tenure.", marginX, y + 7, { width: contentWidth, align: "center" });
    y += 24;
  } else {
    approvedLeaves.slice(0, 10).forEach((l, idx) => {
      const bg = idx % 2 === 0 ? "#FFFFFF" : "#F8FAFC";
      doc.rect(marginX, y, contentWidth, 20).fillAndStroke(bg, "#E2E8F0");

      const s = new Date(l.startDate);
      const e = new Date(l.endDate);
      let diff = 1;
      if (!isNaN(s.getTime()) && !isNaN(e.getTime())) {
        diff = Math.max(1, Math.round((e - s) / (1000 * 60 * 60 * 24)) + 1);
      }

      doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#1E293B").text(l.leaveType || "General", marginX + 10, y + 5);
      doc.font("Helvetica").fillColor("#475569").text(formatDate(l.startDate), marginX + 105, y + 5);
      doc.text(formatDate(l.endDate), marginX + 185, y + 5);
      doc.font("Helvetica-Bold").fillColor("#7C3AED").text(`${diff}d`, marginX + 265, y + 5, { width: 55, align: "center" });
      doc.font("Helvetica").fillColor("#16A34A").text("Approved", marginX + 325, y + 5, { width: 65, align: "center" });
      doc.fillColor("#64748B").text((l.reason || "—").slice(0, 18), marginX + 395, y + 5, { width: 95, ellipsis: true });
      y += 20;
    });
  }

  y += 12;
  doc.font("Helvetica-Oblique").fontSize(8.5).fillColor("#64748B").text("Note: All leave records above reflect certified leave applications registered in company records.", marginX, y);

  renderFooter(doc, "Human Resources Leave Management", orgName);
  return doc;
};
